repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace       # Elimina espacios al final de líneas
      - id: end-of-file-fixer         # Asegura que haya una línea en blanco al final
      - id: check-added-large-files   # Evita subir archivos grandes por accidente
      - id: check-yaml                # Valida archivos YAML si usas alguno
      - id: debug-statements          # Avisa si hay `print` o `pdb` olvidados

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.9  # O el que estés usando

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-builtins", "flake8-bugbear"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        language_version: python3.9  # Si usas tipado estático
