## ───────────────────────────────
## 🧩 Run Individual Steps
## ───────────────────────────────

run:
	@if [ ! -f .env ]; then \
		echo "❌ .env file is missing. Please copy it from .env-example"; \
		exit 1; \
	fi
	./venv/Scripts/python src/main.py $(ARGS) | tee ./logs/run_$(shell date +%Y-%m-%d_%H-%M-%S).log

run-step-1:
	make run ARGS="--steps 1"

run-step-2:
	make run ARGS="--steps 2"

run-step-3:
	make run ARGS="--steps 3"

run-step-4:
	make run ARGS="--steps 4"

run-step-5:
	make run ARGS="--steps 5"

run-step-6:
	make run ARGS="--steps 6"

run-step-7:
	make run ARGS="--steps 7"

run-step-8:
	make run ARGS="--steps 8"

run-step-9:
	make run ARGS="--steps 9"
